config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  get 'pages/index'
  root to: 'pages#index'
  devise_for :users, path: '', path_names: {
    sign_in: 'sign-in',
    sign_out: 'sign-out',
    sign_up: 'sign-up',
    password: 'password',
    confirmation: 'verification'
  }
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :comments, :destroy]
      resources :likes, only: [:create, :destroy]
    end
  end

  namespace :api do
    namespace :v1 do
      post 'login', to: 'login#create'
      resources :users do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
      end
    end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :posts, dependent: :destroy, foreign_key: :author_id
  has_many :comments
  has_many :likes
  validates :name, presence: true
  validates :post_counter, numericality: { greater_than_or_equal_to: 0 }
  validates :post_counter, numericality: { only_integer: true }

  def admin?
    role == 'admin'
  end

  def recent_posts
    posts.includes(comments: [:author]).order(created_at: :desc).limit(3)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  layout 'standard'

  def index
    @users = User.where.not(id: current_user.id)
    @user = User.find_by(id: current_user.id)
  end

  def show
    @user = User.find_by(id: params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<%= link_to user_path(user.id), class: 'userContainer' do %>
  <div class='userImageContainer'>
    <img class='userImage' src=<%= user.photo %> alt='userImage' />
  </div> 
  <div class='userInformationContainer'>
    <h1><%= user.name %></h1>
    <p>Number of posts: <%= user.post_counter %></p>
  </div>
<% end %>

app/views/users/index.html.erb
<% link = root_path %>
<%= render 'shared/navbar', link: link %>
<%= render partial: 'shared/user_info', locals: { user: @user } %>

<h2 class="pageTitle", style="margin-top: 3rem;">Meet People Like You </h1>

<% @users.each do |user| %>
  <%= render partial: 'shared/user_info', locals: { user: user } %>
<% end %>

app/views/users/show.html.erb
<% link = root_path%>
<%= render 'shared/navbar', link: link %>

<%= render partial: 'shared/user_info', locals: { user: @user } %>
<div class='bioContainer'>
  <h1> Bio </h1>
  <p> <%= @user.bio %> </p>
</div>

<% if @user == current_user %>
  <%= link_to new_user_post_path(@user), class: 'newPostButton button' do %>
    Create New Post
  <% end %>
<% end %>

<%= render partial: "shared/post", collection: @user.recent_posts %>
<%= link_to user_posts_path(@user), class: 'button' do %>
  See All People's Posts
<% end %>