config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  get 'pages/index'
  root to: 'pages#index'
  devise_for :users, path: '', path_names: {
    sign_in: 'sign-in',
    sign_out: 'sign-out',
    sign_up: 'sign-up',
    password: 'password',
    confirmation: 'verification'
  }
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :comments, :destroy]
      resources :likes, only: [:create, :destroy]
    end
  end

  namespace :api do
    namespace :v1 do
      post 'login', to: 'login#create'
      resources :users do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
      end
    end
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.admin?
      can :manage, :all
    else
      can :read, :all
      can :manage, Post, author_id: user.id
      can :manage, Comment, author_id: user.id
      can :manage, Like, author_id: user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  belongs_to :post
  after_save :update_comments_counter
  after_destroy :decrease_comments_counter
  validates :text, presence: true, length: { in: 2..100 }

  def update_comments_counter
    post.increment!(:comments_counter)
  end

  def decrease_comments_counter
    post.decrement!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post, foreign_key: :post_id
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  after_save :update_likes_counter

  def update_likes_counter
    post.increment!(:likes_counter)
  end

  def decrease_likes_counter
    post.decrement!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :comments, dependent: :destroy, foreign_key: :post_id
  has_many :likes, dependent: :destroy, foreign_key: :post_id
  after_save :update_posts_counter
  after_destroy :decrease_posts_counter
  validates :title, presence: true
  validates :title, length: { maximum: 250 }
  validates :comments_counter, numericality: { greater_than_or_equal_to: 0 }
  validates :comments_counter, numericality: { only_integer: true }
  validates :likes_counter, numericality: { greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true }

  def update_posts_counter
    author.increment!(:post_counter)
  end

  def recent_comments
    comments.includes(:post, post: [:author]).order(created_at: :asc).limit(5)
  end

  def decrease_posts_counter
    author.decrement!(:post_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :posts, dependent: :destroy, foreign_key: :author_id
  has_many :comments
  has_many :likes
  validates :name, presence: true
  validates :post_counter, numericality: { greater_than_or_equal_to: 0 }
  validates :post_counter, numericality: { only_integer: true }

  def admin?
    role == 'admin'
  end

  def recent_posts
    posts.includes(comments: [:author]).order(created_at: :desc).limit(3)
  end
end

app/controllers/api/v1/login_controller.rb
require 'jwt'
require 'knock'

class Api::V1::LoginController < Api::V1::ApplicationController
  def create
    user = User.find_by(email: params[:email])

    if user&.valid_password?(params[:password])
      token = generate_jwt_token(user)
      render json: { api_token: token }
    else
      render json: { error: 'Invalid email or password' }, status: :unauthorized
    end
  end

  private

  def generate_jwt_token(user)
    Knock::AuthToken.new(payload: { sub: user.id }).token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email photo bio])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name email])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  layout 'standard'
  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.author = current_user
    @comment.post = Post.find(params[:post_id])

    respond_to do |format|
      if @comment.save
        format.html do
          redirect_to user_post_path(params[:user_id], params[:post_id]), notice: 'Comment was successfully created.'
        end
      else
        format.html { render :new }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.html do
        redirect_to user_post_path(params[:user_id], params[:post_id]), notice: 'Comment was successfully destroyed.'
      end
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.new
    @like.author = User.includes(posts: [{ comments: [:author] }]).find(current_user.id)
    @like.post = Post.find(params[:post_id])

    @like.save! unless Like.exists?(author: @like.author, post: @like.post)

    respond_to do |format|
      format.html { redirect_to user_post_path(@like.author.id, @like.post.id) }
    end
  end

  def destroy
    @like = Like.find_by(author_id: current_user.id, post_id: params[:id])

    if @like
      @like.decrease_likes_counter
      @like.destroy
    end

    respond_to do |format|
      format.html { redirect_to user_post_path(current_user.id, params[:id]) }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    return unless user_signed_in?

    redirect_to users_path
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  layout 'standard'

  def index
    @posts = Post.includes(comments: [:author]).all
  end

  def show
    @post = Post.includes(comments: [:author]).find(params[:id])
    @like = Like.includes(post: :author).find_by(author: current_user, post: @post)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to user_posts_path(current_user), notice: 'Post was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path, notice: 'Post deleted successfully.'
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  layout 'standard'

  def index
    @users = User.where.not(id: current_user.id)
    @user = User.find_by(id: current_user.id)
  end

  def show
    @user = User.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def can_delete?(item)
    current_user.admin? || current_user.id == item.author_id
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Minimalistic Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_include_tag 'rails-ujs' %>
    <%= turbo_include_tags %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="icon" href="https://i.pinimg.com/originals/a8/6f/6f/a86f6fcbce14caef74f62cf2d3df7552.png" type="image/png">
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/layouts/standard.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns = "http://www.w3.org/1999/xhtml">

   <head>
      <meta http-equiv = "Content-Type" content = "text/html; charset = iso-8859-1" />
      <meta http-equiv = "Content-Language" content = "en-us" />
      <title>Blog Application</title>
      <%= stylesheet_link_tag "style" %>
      <link rel="icon" href="https://i.pinimg.com/originals/a8/6f/6f/a86f6fcbce14caef74f62cf2d3df7552.png" type="image/png">
      <%= csrf_meta_tags %>
      <%= javascript_include_tag 'rails-ujs' %>
      <%= turbo_include_tags %>
   </head>

   <body id = "library">
      <div id = "container">
         <div id = "generalContainer">
            <%= yield -%>
         </div>
         
      </div>
   <script src="https://kit.fontawesome.com/001e3526ee.js" crossorigin="anonymous"></script>
   </body>
   
</html>

app/views/pages/index.html.erb
<div class='wellcomeContainer'>
  <h1>Welcome to your Personal Minimalistic Blog !!</h1>
  <ul>
    <li><%= link_to 'Sign in', new_user_registration_path, class: "button" %></li>
    <li><%= link_to 'Log in', new_user_session_path, class: "button" %></li>
  </ul>
</div>

app/views/shared/_comment_form.html.erb
<%= form_with model: @comment, url: user_post_comments_path, local: true, class: "createCommentForm" do |form| %>
  <%= form.text_field :text, class: "commentTextArea", placeholder: "Enter your comment here" %>
  <%= form.submit "Add comment", class: "commentSubmitButton button" %>
<% end %>

app/views/shared/_form.html.erb
<%= form_with model: @post, url: user_posts_path, local: true do |form| %>
  <%= form.text_field :title, class:'formInput', placeholder: 'Title' %>
  <%= form.text_area :text, class: 'formText', placeholder: 'Content' %>
  <%= form.submit "Create New Post", class: 'formButton' %>
<% end %>

app/views/shared/_like.html.erb
<% if like %>
  <%= form_with(model: like, url: user_post_like_path(current_user, post), local: true, method: :delete, data: { turbo_method: :delete }) do |form| %>
    <%= form.submit "Unlike", class: "likeButton button", data: { turbo_frame: "false" } %>
  <% end %>
<% else %>
  <%= form_with(model: like, url: user_post_likes_path(current_user, post), local: true, method: :create, data: { turbo_method: :post }) do |form| %>
    <%= form.submit "Like", class: "likeButton button", data: { turbo_frame: "false" } %>
  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <%= link_to "Back", link || root_path, class: 'backButton button', data: { turbolinks: 'false' } %>
  <%= link_to users_path, class: 'homeButton' do %>
    <img src="<%= asset_path('favicon.svg') %>" alt="Home">
  <% end %>
  <%= link_to "Log Out", destroy_user_session_path, method: :get, class: "button logOut" %>
</div>

app/views/shared/_post.html.erb
<div class="postContainer">
  <%= link_to user_post_path(current_user.id, post), class: 'linkToPost postTitle' do %>
    <%= post.title %>
  <% end %>
  <p class="postText"> <%= post.text %></p>
  <div class="postInteractionContainer">
    <p> Comments: <%= post.comments_counter %></p>
    <p> Likes: <%= post.likes_counter %></p>
  </div>
  <% if can_delete?(post)%>
    <%= link_to 'Delete', user_post_path(post.author_id, post), method: :delete, data: { confirm: 'Delete Post?' }, class: "deletePostBtn" %>
  <% end %>
</div>

app/views/shared/_user_info.html.erb
<%= link_to user_path(user), class: 'userContainer' do %>
  <div class='userImageContainer'>
    <img class='userImage' src=<%= user.photo %> alt='userImage' />
  </div> 
  <div class='userInformationContainer'>
    <h1><%= user.name %></h1>
    <p>Number of posts: <%= user.post_counter %></p>
  </div>
<% end %>