config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  get 'pages/index'
  root to: 'pages#index'
  devise_for :users, path: '', path_names: {
    sign_in: 'sign-in',
    sign_out: 'sign-out',
    sign_up: 'sign-up',
    password: 'password',
    confirmation: 'verification'
  }
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :comments, :destroy]
      resources :likes, only: [:create, :destroy]
    end
  end

  namespace :api do
    namespace :v1 do
      post 'login', to: 'login#create'
      resources :users do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
      end
    end
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :comments, dependent: :destroy, foreign_key: :post_id
  has_many :likes, dependent: :destroy, foreign_key: :post_id
  after_save :update_posts_counter
  after_destroy :decrease_posts_counter
  validates :title, presence: true
  validates :title, length: { maximum: 250 }
  validates :comments_counter, numericality: { greater_than_or_equal_to: 0 }
  validates :comments_counter, numericality: { only_integer: true }
  validates :likes_counter, numericality: { greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true }

  def update_posts_counter
    author.increment!(:post_counter)
  end

  def recent_comments
    comments.includes(:post, post: [:author]).order(created_at: :asc).limit(5)
  end

  def decrease_posts_counter
    author.decrement!(:post_counter)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < Api::V1::ApplicationController
  before_action :authenticate_user
  def index
    posts = User.find(params['user_id']).posts
    render json: posts
  rescue StandardError
    render json: { error: 'User not found' }, status: :bad_request
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  layout 'standard'

  def index
    @posts = Post.includes(comments: [:author]).all
  end

  def show
    @post = Post.includes(comments: [:author]).find(params[:id])
    @like = Like.includes(post: :author).find_by(author: current_user, post: @post)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to user_posts_path(current_user), notice: 'Post was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path, notice: 'Post deleted successfully.'
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment.html.erb
<div class="commentContainer">
  <p class='commentInfo'> <%= comment.author.name %>: </p>
  <p class='commentText'> <%= comment.text %> </p>

  <% if can_delete?(comment) %>
    <%= link_to 'Delete Comment', user_post_comment_path(current_user.id, comment.post, comment), method: :delete, data: { confirm: 'Delete Comment?' }, class: "deleteCommentBtn" %>
  <% end %>
</div>

app/views/posts/index.html.erb
<% link = root_path %>
<%= render 'shared/navbar', link: link %>

<h1 class='pageTitle'>All Community Posts</h1>
<%= render partial: 'shared/user_info', locals: { user: current_user } %>

<div class="indexPostContainer">
    <% @posts.each do | post |%>
     <%= render partial: 'shared/post', object: post%>
     <div class='commentsContainer'>
       <%= render partial: 'comment', collection: post.recent_comments %>
     </div>
    <% end %>
</div>

<button class="button">Pagination</button>

app/views/posts/new.html.erb
<div class='formContainer'>
  <%= render partial: "shared/form", locals: { post: @post } %>
</div>

app/views/posts/show.html.erb
<% link = user_path(@post.author)%>
<%= render 'shared/navbar', link: link %>

<% if flash[:alert] %>
  <div class="flash alert"><%= flash[:alert] %></div>
<%elsif flash[:notice]%>
  <div class="flash notice"><%= flash[:notice] %></div>
<% end %>

<div class="postShowContainer">
  <div class="postShowInfo">
    <div class="mainInfo">
      <h3> <%= @post.title %> by <%= @post.author.name %> </h3>
      <p>Comments: <%= @post.comments_counter %>,
        Likes: <%= @post.likes_counter %></p>
      <%= render partial: "shared/like", locals: { like: @like, post: @post } %>
    </div>
    <p class="postText"> <%= @post.text %> </p>
  </div>
  <div class='showCommentsContainer'>
    <%= render partial: 'comment', collection: @post.comments %>
    <%= link_to new_user_post_comment_path(current_user, @post), class: 'commentSubmitButton button' do %>
      Add New Comment
    <% end %>
  </div>
</div>